import {
  CakePresetStyle,
  RealisticCakeConfig,
  CakeShapeType,
  CakeFlavorType,
  IcingFinishType,
  CakeBorderStyle,
  CakePlateStyleType,
  CakeDecorationItem,
  TopperMaterial,
} from '../types/cake';

export const CAKE_PRESETS: Record<CakePresetStyle, { name: string; description: string; defaults: Partial<RealisticCakeConfig> }> = {
  luxury_floral: {
    name: 'Luxury Floral Cake',
    description: 'Soft ivory buttercream with handcrafted edible sugar peonies and delicate pearl borders.',
    defaults: {
      style: 'luxury_floral',
      shape: 'round',
      flavorLabel: 'vanilla',
      frostingColor: '#FAF5EE',
      baseColor: '#E6D3B3',
      accentColor: '#F472B6',
      icingStyle: 'textured_floral',
      borderStyle: 'pearl_border',
      plateStyle: 'gold_metallic',
      decorations: ['edible_flowers', 'gold_leaf_flakes'],
      decorationIntensity: 'balanced',
      topperMaterial: 'gold_acrylic',
      candleColor: '#F59E0B',
    },
  },
  chocolate_drip: {
    name: 'Chocolate Ganache Drip',
    description: 'Decadent Belgian dark chocolate sponge drenched in high-gloss ganache drip with chocolate curls.',
    defaults: {
      style: 'chocolate_drip',
      shape: 'round',
      flavorLabel: 'chocolate',
      frostingColor: '#3B1E12',
      baseColor: '#27140B',
      accentColor: '#D97706',
      icingStyle: 'drip_icing',
      borderStyle: 'swirl_border',
      plateStyle: 'gold_metallic',
      decorations: ['chocolate_shards', 'gold_leaf_flakes', 'cherries'],
      decorationIntensity: 'rich',
      topperMaterial: 'gold_acrylic',
      candleColor: '#F59E0B',
    },
  },
  minimal_white: {
    name: 'Minimal White Porcelain',
    description: 'Clean architectural lines, smooth silk buttercream, and understated contemporary luxury.',
    defaults: {
      style: 'minimal_white',
      shape: 'round',
      flavorLabel: 'vanilla',
      frostingColor: '#FFFFFF',
      baseColor: '#F1ECE4',
      accentColor: '#CBD5E1',
      icingStyle: 'smooth_buttercream',
      borderStyle: 'minimal_clean',
      plateStyle: 'white_porcelain',
      decorations: ['gold_leaf_flakes'],
      decorationIntensity: 'minimal',
      topperMaterial: 'silver_acrylic',
      candleColor: '#94A3B8',
    },
  },
  pink_rose: {
    name: 'Pink Rose & Macarons',
    description: 'Blush pink whipped cream crowned with French raspberry macarons and rose petals.',
    defaults: {
      style: 'pink_rose',
      shape: 'round',
      flavorLabel: 'strawberry',
      frostingColor: '#FCE7F3',
      baseColor: '#F472B6',
      accentColor: '#EC4899',
      icingStyle: 'whipped_cream',
      borderStyle: 'piped_floral',
      plateStyle: 'pastel_ceramic',
      decorations: ['macarons', 'edible_flowers', 'mini_hearts'],
      decorationIntensity: 'rich',
      topperMaterial: 'gold_acrylic',
      candleColor: '#EC4899',
    },
  },
  black_gold: {
    name: 'Black & Gold Noir',
    description: 'Moody noir velvet buttercream, 24k gold leaf foil accents, and black marble presentation.',
    defaults: {
      style: 'black_gold',
      shape: 'two_tier',
      flavorLabel: 'black_forest',
      frostingColor: '#171717',
      baseColor: '#0F0F0F',
      accentColor: '#F59E0B',
      icingStyle: 'chocolate_glaze',
      borderStyle: 'minimal_clean',
      plateStyle: 'black_marble',
      decorations: ['gold_leaf_flakes', 'chocolate_shards'],
      decorationIntensity: 'balanced',
      topperMaterial: 'gold_acrylic',
      candleColor: '#EAB308',
    },
  },
  galaxy: {
    name: 'Galaxy Cosmic Mirror',
    description: 'Deep cosmic violet and nebula marble glaze with fondant stars and glittering edible dust.',
    defaults: {
      style: 'galaxy',
      shape: 'round',
      flavorLabel: 'custom',
      frostingColor: '#4C1D95',
      baseColor: '#1E1B4B',
      accentColor: '#818CF8',
      icingStyle: 'chocolate_glaze',
      borderStyle: 'swirl_border',
      plateStyle: 'black_marble',
      decorations: ['star_fondant', 'metallic_sprinkles'],
      decorationIntensity: 'rich',
      topperMaterial: 'neon_acrylic',
      candleColor: '#C084FC',
    },
  },
  red_velvet_heart: {
    name: 'Red Velvet Heart',
    description: 'Crimson cocoa velvet crumb layered with cream cheese swirl and fresh wild berries.',
    defaults: {
      style: 'red_velvet_heart',
      shape: 'heart',
      flavorLabel: 'red_velvet',
      frostingColor: '#FFFBEB',
      baseColor: '#991B1B',
      accentColor: '#DC2626',
      icingStyle: 'whipped_cream',
      borderStyle: 'piped_floral',
      plateStyle: 'white_porcelain',
      decorations: ['fresh_berries', 'cherries'],
      decorationIntensity: 'balanced',
      topperMaterial: 'gold_acrylic',
      candleColor: '#EF4444',
    },
  },
  funfetti_party: {
    name: 'Funfetti Rainbow Party',
    description: 'Cheery festive vanilla sponge studded with rainbow sprinkles and colorful celebration candles.',
    defaults: {
      style: 'funfetti_party',
      shape: 'round',
      flavorLabel: 'butterscotch',
      frostingColor: '#FEF9C3',
      baseColor: '#FDE047',
      accentColor: '#06B6D4',
      icingStyle: 'smooth_buttercream',
      borderStyle: 'pearl_border',
      plateStyle: 'pastel_ceramic',
      decorations: ['metallic_sprinkles', 'balloon_topper'],
      decorationIntensity: 'rich',
      topperMaterial: 'neon_acrylic',
      candleColor: '#3B82F6',
    },
  },
};

export const FLAVOR_OPTIONS: { id: CakeFlavorType; label: string; baseHex: string }[] = [
  { id: 'chocolate', label: 'Belgian Chocolate', baseHex: '#381E11' },
  { id: 'vanilla', label: 'Madagascar Vanilla', baseHex: '#E8D5B5' },
  { id: 'red_velvet', label: 'Royal Red Velvet', baseHex: '#881337' },
  { id: 'butterscotch', label: 'Butterscotch Crunch', baseHex: '#D97706' },
  { id: 'strawberry', label: 'Wild Strawberry', baseHex: '#FB7185' },
  { id: 'black_forest', label: 'Black Forest Cherry', baseHex: '#1F110B' },
  { id: 'custom', label: 'Custom Palette', baseHex: '#4C1D95' },
];

export const DECORATION_OPTIONS: { id: CakeDecorationItem; label: string }[] = [
  { id: 'metallic_sprinkles', label: 'Metallic Sprinkles' },
  { id: 'chocolate_shards', label: 'Chocolate Shards' },
  { id: 'fresh_berries', label: 'Fresh Wild Berries' },
  { id: 'cherries', label: 'Glossy Glacé Cherries' },
  { id: 'edible_flowers', label: 'Sugar Peonies & Blossoms' },
  { id: 'gold_leaf_flakes', label: '24K Gold Leaf Flakes' },
  { id: 'macarons', label: 'French Macarons' },
  { id: 'mini_hearts', label: 'Fondant Mini Hearts' },
  { id: 'star_fondant', label: 'Golden Stars' },
  { id: 'balloon_topper', label: 'Mini Balloon Cluster' },
];

export const TOPPER_MATERIALS: { id: TopperMaterial; label: string; previewClass: string }[] = [
  { id: 'gold_acrylic', label: 'Mirror Gold Acrylic', previewClass: 'from-amber-200 via-yellow-400 to-amber-600' },
  { id: 'silver_acrylic', label: 'Brushed Silver Acrylic', previewClass: 'from-slate-200 via-gray-300 to-slate-400' },
  { id: 'neon_acrylic', label: 'Glowing Neon Acrylic', previewClass: 'from-cyan-300 via-fuchsia-400 to-pink-500' },
  { id: 'chocolate_lettering', label: 'Poured Chocolate', previewClass: 'from-amber-950 via-stone-900 to-amber-900' },
  { id: 'fondant_lettering', label: 'Hand-sculpted Fondant', previewClass: 'from-rose-100 via-pink-200 to-rose-300' },
  { id: 'edible_plaque', label: 'Sugar Parchment Plaque', previewClass: 'from-amber-50 via-amber-100 to-amber-200' },
];
