import { TemplateDefinition } from '../types/birthday';

export const BIRTHDAY_TEMPLATES: TemplateDefinition[] = [
  {
    id: 'royal-gold',
    title: 'Royal Gold Celebration',
    description: 'Luxurious gold gradients, regal black accents, and glowing starlight for a majestic milestone.',
    tags: ['Premium', 'Elegant', 'Milestone', 'Family'],
    previewGradient: 'from-amber-700 via-amber-900 to-stone-950',
    accentBadge: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
    cakeDefaults: {
      style: 'luxury_floral',
      shape: 'two_tier',
      flavorLabel: 'chocolate',
      frostingColor: '#D97706',
      baseColor: '#78350F',
      icingStyle: 'drip_icing',
      decorations: ['gold_leaf_flakes', 'star_fondant'],
      plateStyle: 'gold_metallic',
      candleColor: '#F59E0B',
      topperMaterial: 'gold_acrylic',
    },
    themeDefaults: {
      templateId: 'royal-gold',
      backgroundType: 'stars',
      primaryColor: '#D97706',
      secondaryColor: '#B45309',
      accentColor: '#FCD34D',
      textColor: '#FEF3C7',
      fontStyle: 'elegant',
      animationIntensity: 'balanced',
      celebrationStyle: 'sparkles',
      toggles: {
        showFloatingDecorations: true,
        showCountdown: true,
        showPhotoCarousel: true,
        showMemoryTimeline: true,
        showGuestbook: true,
        showReactionButtons: true,
        polaroidStyle: false,
      },
    },
  },
  {
    id: 'pink-love-story',
    title: 'Pink Love Story',
    description: 'Romantic pastel pinks, rose gold shimmer, and delicate floating hearts crafted with deep love.',
    tags: ['Romantic', 'Partner', 'Cute'],
    previewGradient: 'from-rose-500 via-pink-600 to-purple-950',
    accentBadge: 'bg-rose-500/20 text-rose-300 border-rose-500/40',
    cakeDefaults: {
      style: 'pink_rose',
      shape: 'heart',
      flavorLabel: 'strawberry',
      frostingColor: '#FCE7F3',
      baseColor: '#FB7185',
      icingStyle: 'whipped_cream',
      decorations: ['edible_flowers', 'macarons', 'mini_hearts'],
      plateStyle: 'pastel_ceramic',
      candleColor: '#EC4899',
      topperMaterial: 'gold_acrylic',
    },
    themeDefaults: {
      templateId: 'pink-love-story',
      backgroundType: 'floating_hearts',
      primaryColor: '#EC4899',
      secondaryColor: '#F43F5E',
      accentColor: '#FBCFE8',
      textColor: '#FFF1F2',
      fontStyle: 'handwritten',
      animationIntensity: 'balanced',
      celebrationStyle: 'hearts',
      toggles: {
        showFloatingDecorations: true,
        showCountdown: true,
        showPhotoCarousel: true,
        showMemoryTimeline: true,
        showGuestbook: true,
        showReactionButtons: true,
        polaroidStyle: true,
      },
    },
  },
  {
    id: 'midnight-neon-party',
    title: 'Midnight Neon Party',
    description: 'Electric cyan, hot magenta, and cyberpunk laser energy built for dancing and loud celebrations.',
    tags: ['Fun', 'Party', 'Best Friend'],
    previewGradient: 'from-cyan-900 via-fuchsia-900 to-slate-950',
    accentBadge: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40',
    cakeDefaults: {
      style: 'galaxy',
      shape: 'round',
      flavorLabel: 'custom',
      frostingColor: '#06B6D4',
      baseColor: '#4C1D95',
      icingStyle: 'drip_icing',
      decorations: ['star_fondant', 'metallic_sprinkles'],
      plateStyle: 'black_marble',
      candleColor: '#F43F5E',
      topperMaterial: 'neon_acrylic',
    },
    themeDefaults: {
      templateId: 'midnight-neon-party',
      backgroundType: 'gradient',
      primaryColor: '#06B6D4',
      secondaryColor: '#D946EF',
      accentColor: '#38BDF8',
      textColor: '#F0FDFA',
      fontStyle: 'bold_party',
      animationIntensity: 'extra',
      celebrationStyle: 'fireworks',
      toggles: {
        showFloatingDecorations: true,
        showCountdown: true,
        showPhotoCarousel: true,
        showMemoryTimeline: true,
        showGuestbook: true,
        showReactionButtons: true,
        polaroidStyle: false,
      },
    },
  },
  {
    id: 'cute-cartoon-confetti',
    title: 'Cute Cartoon Confetti',
    description: 'Playful doodle aesthetics, cheerful pastel hues, and bouncy animations for pure joy.',
    tags: ['Cute', 'Best Friend', 'Fun'],
    previewGradient: 'from-amber-400 via-orange-400 to-rose-400',
    accentBadge: 'bg-amber-500/20 text-amber-200 border-amber-400/40',
    cakeDefaults: {
      style: 'funfetti_party',
      shape: 'round',
      flavorLabel: 'vanilla',
      frostingColor: '#FEF9C3',
      baseColor: '#F472B6',
      icingStyle: 'smooth_buttercream',
      decorations: ['metallic_sprinkles', 'cherries', 'balloon_topper'],
      plateStyle: 'pastel_ceramic',
      candleColor: '#3B82F6',
      topperMaterial: 'neon_acrylic',
    },
    themeDefaults: {
      templateId: 'cute-cartoon-confetti',
      backgroundType: 'confetti',
      primaryColor: '#F59E0B',
      secondaryColor: '#EC4899',
      accentColor: '#10B981',
      textColor: '#FFFBEB',
      fontStyle: 'playful',
      animationIntensity: 'extra',
      celebrationStyle: 'confetti',
      toggles: {
        showFloatingDecorations: true,
        showCountdown: true,
        showPhotoCarousel: true,
        showMemoryTimeline: true,
        showGuestbook: true,
        showReactionButtons: true,
        polaroidStyle: true,
      },
    },
  },
  {
    id: 'sky-blue-balloon-world',
    title: 'Sky Blue Balloon World',
    description: 'Dreamy sky blues, fluffy clouds, and soaring colorful balloons for uplifting birthday spirits.',
    tags: ['Family', 'Cute', 'Peaceful'],
    previewGradient: 'from-sky-500 via-blue-600 to-indigo-950',
    accentBadge: 'bg-sky-500/20 text-sky-300 border-sky-500/40',
    cakeDefaults: {
      style: 'funfetti_party',
      shape: 'round',
      flavorLabel: 'butterscotch',
      frostingColor: '#BAE6FD',
      baseColor: '#0284C7',
      icingStyle: 'whipped_cream',
      decorations: ['balloon_topper', 'star_fondant'],
      plateStyle: 'white_porcelain',
      candleColor: '#FACC15',
      topperMaterial: 'silver_acrylic',
    },
    themeDefaults: {
      templateId: 'sky-blue-balloon-world',
      backgroundType: 'clouds',
      primaryColor: '#0284C7',
      secondaryColor: '#38BDF8',
      accentColor: '#BAE6FD',
      textColor: '#F0F9FF',
      fontStyle: 'modern',
      animationIntensity: 'balanced',
      celebrationStyle: 'balloons',
      toggles: {
        showFloatingDecorations: true,
        showCountdown: true,
        showPhotoCarousel: true,
        showMemoryTimeline: true,
        showGuestbook: true,
        showReactionButtons: true,
        polaroidStyle: false,
      },
    },
  },
  {
    id: 'minimal-elegant-black-gold',
    title: 'Minimal Elegant Black & Gold',
    description: 'Understated high-end luxury with sharp typography, noir minimalism, and polished gold trim.',
    tags: ['Premium', 'Partner', 'Milestone'],
    previewGradient: 'from-stone-900 via-neutral-900 to-black',
    accentBadge: 'bg-amber-400/10 text-amber-200 border-amber-400/30',
    cakeDefaults: {
      style: 'black_gold',
      shape: 'round',
      flavorLabel: 'chocolate',
      frostingColor: '#171717',
      baseColor: '#CA8A04',
      icingStyle: 'smooth_buttercream',
      decorations: ['gold_leaf_flakes'],
      plateStyle: 'black_marble',
      candleColor: '#EAB308',
      topperMaterial: 'gold_acrylic',
    },
    themeDefaults: {
      templateId: 'minimal-elegant-black-gold',
      backgroundType: 'solid',
      primaryColor: '#EAB308',
      secondaryColor: '#CA8A04',
      accentColor: '#FEF08A',
      textColor: '#FAFAFA',
      fontStyle: 'elegant',
      animationIntensity: 'minimal',
      celebrationStyle: 'sparkles',
      toggles: {
        showFloatingDecorations: false,
        showCountdown: true,
        showPhotoCarousel: true,
        showMemoryTimeline: true,
        showGuestbook: true,
        showReactionButtons: true,
        polaroidStyle: false,
      },
    },
  },
  {
    id: 'retro-polaroid-memories',
    title: 'Retro Polaroid Memories',
    description: 'Warm vintage film grain, sepia nostalgia, and tape-stuck Polaroid photo frames for timeless bonds.',
    tags: ['Best Friend', 'Romantic', 'Nostalgic'],
    previewGradient: 'from-amber-900 via-stone-800 to-amber-950',
    accentBadge: 'bg-orange-500/20 text-orange-300 border-orange-500/40',
    cakeDefaults: {
      style: 'chocolate_drip',
      shape: 'round',
      flavorLabel: 'red_velvet',
      frostingColor: '#D97706',
      baseColor: '#78350F',
      icingStyle: 'drip_icing',
      decorations: ['cherries', 'metallic_sprinkles'],
      plateStyle: 'white_porcelain',
      candleColor: '#F97316',
      topperMaterial: 'gold_acrylic',
    },
    themeDefaults: {
      templateId: 'retro-polaroid-memories',
      backgroundType: 'gradient',
      primaryColor: '#EA580C',
      secondaryColor: '#D97706',
      accentColor: '#FED7AA',
      textColor: '#FFF7ED',
      fontStyle: 'handwritten',
      animationIntensity: 'balanced',
      celebrationStyle: 'confetti',
      toggles: {
        showFloatingDecorations: true,
        showCountdown: true,
        showPhotoCarousel: true,
        showMemoryTimeline: true,
        showGuestbook: true,
        showReactionButtons: true,
        polaroidStyle: true,
      },
    },
  },
  {
    id: 'galaxy-birthday-universe',
    title: 'Galaxy Birthday Universe',
    description: 'Deep cosmic violet, pulsing nebulas, and constellations radiating infinite birthday love.',
    tags: ['Premium', 'Partner', 'Best Friend'],
    previewGradient: 'from-violet-950 via-indigo-950 to-slate-950',
    accentBadge: 'bg-violet-500/20 text-violet-300 border-violet-500/40',
    cakeDefaults: {
      style: 'galaxy',
      shape: 'two_tier',
      flavorLabel: 'chocolate',
      frostingColor: '#4C1D95',
      baseColor: '#1E1B4B',
      icingStyle: 'chocolate_glaze',
      decorations: ['star_fondant', 'gold_leaf_flakes'],
      plateStyle: 'black_marble',
      candleColor: '#C084FC',
      topperMaterial: 'neon_acrylic',
    },
    themeDefaults: {
      templateId: 'galaxy-birthday-universe',
      backgroundType: 'galaxy',
      primaryColor: '#8B5CF6',
      secondaryColor: '#6366F1',
      accentColor: '#DDD6FE',
      textColor: '#F5F3FF',
      fontStyle: 'modern',
      animationIntensity: 'extra',
      celebrationStyle: 'stars',
      toggles: {
        showFloatingDecorations: true,
        showCountdown: true,
        showPhotoCarousel: true,
        showMemoryTimeline: true,
        showGuestbook: true,
        showReactionButtons: true,
        polaroidStyle: false,
      },
    },
  },
  {
    id: 'floral-garden-party',
    title: 'Floral Garden Party',
    description: 'Blossoming petals, lush sage greens, and soft peony bouquets reflecting growth and kindness.',
    tags: ['Family', 'Romantic', 'Elegant'],
    previewGradient: 'from-emerald-900 via-teal-900 to-stone-900',
    accentBadge: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
    cakeDefaults: {
      style: 'luxury_floral',
      shape: 'round',
      flavorLabel: 'vanilla',
      frostingColor: '#ECFDF5',
      baseColor: '#047857',
      icingStyle: 'textured_floral',
      decorations: ['edible_flowers', 'macarons'],
      plateStyle: 'pastel_ceramic',
      candleColor: '#34D399',
      topperMaterial: 'gold_acrylic',
    },
    themeDefaults: {
      templateId: 'floral-garden-party',
      backgroundType: 'floral',
      primaryColor: '#10B981',
      secondaryColor: '#059669',
      accentColor: '#A7F3D0',
      textColor: '#ECFDF5',
      fontStyle: 'elegant',
      animationIntensity: 'balanced',
      celebrationStyle: 'sparkles',
      toggles: {
        showFloatingDecorations: true,
        showCountdown: true,
        showPhotoCarousel: true,
        showMemoryTimeline: true,
        showGuestbook: true,
        showReactionButtons: true,
        polaroidStyle: false,
      },
    },
  },
  {
    id: 'bollywood-celebration',
    title: 'Bollywood Celebration',
    description: 'Vibrant marigold yellows, royal rani pink, dhol beats, and filmi magic for full-on celebration.',
    tags: ['Fun', 'Family', 'Best Friend'],
    previewGradient: 'from-amber-600 via-pink-700 to-purple-950',
    accentBadge: 'bg-pink-500/20 text-pink-300 border-pink-500/40',
    cakeDefaults: {
      style: 'luxury_floral',
      shape: 'two_tier',
      flavorLabel: 'butterscotch',
      frostingColor: '#F59E0B',
      baseColor: '#DB2777',
      icingStyle: 'drip_icing',
      decorations: ['edible_flowers', 'gold_leaf_flakes', 'star_fondant'],
      plateStyle: 'gold_metallic',
      candleColor: '#F43F5E',
      topperMaterial: 'gold_acrylic',
    },
    themeDefaults: {
      templateId: 'bollywood-celebration',
      backgroundType: 'balloons',
      primaryColor: '#F59E0B',
      secondaryColor: '#DB2777',
      accentColor: '#FDE68A',
      textColor: '#FFFBEB',
      fontStyle: 'bold_party',
      animationIntensity: 'extra',
      celebrationStyle: 'fireworks',
      toggles: {
        showFloatingDecorations: true,
        showCountdown: true,
        showPhotoCarousel: true,
        showMemoryTimeline: true,
        showGuestbook: true,
        showReactionButtons: true,
        polaroidStyle: false,
      },
    },
  },
];
